FROM fedora:45

ARG USERNAME=test
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

COPY assets/scripts/*.sh /tmp/scripts/

RUN dnf -y install dnf-plugins-core \
    && dnf -y update \
    && dnf -y install openssl hostname sudo file which telnet nc jq \
       voms-clients-cpp voms-clients-java \
       python3-pip python3-devel python3-setuptools \
    && sh /tmp/scripts/provide-user.sh ${USERNAME} ${USER_UID} ${USER_GID} \
    && mkdir /home/${USERNAME}/.config /home/${USERNAME}/.globus \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME} \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install --upgrade robotframework \
    && python3 -m pip install --upgrade robotframework-httplibrary \
    && python3 -m pip install --upgrade requests \
    && python3 -m pip install --upgrade pyyaml \
    && rm -rf /tmp/scripts

USER ${USERNAME}
WORKDIR /home/${USERNAME}
