FROM almalinux:9

ARG RHEL_VERSION=9
ARG VOMS_REPO=stable

ENV VOMS_REPO_URL=https://italiangrid.github.io/voms-repo/repofiles/rhel/voms-${VOMS_REPO}-el${RHEL_VERSION}.repo

RUN dnf -y install epel-release dnf-plugins-core \
  && dnf config-manager --add-repo ${VOMS_REPO_URL} \
  && dnf -y update \
  && dnf -y install which wget sudo file util-linux-user voms-mysql-plugin voms-server \
  && dnf clean all \
  && echo voms ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/voms # voms-server adds the voms user \
  && chmod 0440 /etc/sudoers.d/voms \
  && update-crypto-policies --set LEGACY
