#!/usr/bin/env groovy
def image, name, variables

pipeline {
  agent { label 'docker' }

  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5'))
    ansiColor('xterm')
    timestamps()
  }

  parameters {
    string(defaultValue: "", description: 'Robot arguments', name: 'ROBOT_ARGS')
  }

  environment {
    ROBOT_ARGS = "${params.ROBOT_ARGS}"
  }

  stages {
    stage ('run'){
      steps {
        script {
          sh returnStatus: true, script: '''#!/bin/bash 
          set -ex
          cd compose
          docker-compose -f docker-compose.ci.yml up trust
          docker-compose -f docker-compose.ci.yml up testsuite
          '''
        }
      }
    }

    stage('report'){
      steps {
        sh "docker cp voms-testsuite_voms_1:/tmp/reports ."
        archive 'reports/**'

        step([$class: 'RobotPublisher',
          disableArchiveOutput: false,
          logFileName: 'log.html',
          otherFiles: '*.png',
          outputFileName: 'output.xml',
          outputPath: "reports",
          passThreshold: 100,
          reportFileName: 'report.html',
          unstableThreshold: 90])
      }
    }
  }

  post {
    failure {
      slackSend color: 'danger', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Failure (<${env.BUILD_URL}|Open>)"
    }

    changed {
      script{
        if('SUCCESS'.equals(currentBuild.currentResult)) {
          slackSend color: 'good', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Back to normal (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
