version: '3.7'

services:

  trust:
    image: indigoiam/egi-trustanchors
    volumes:
      - trustanchors:/tmp/certificates
      - cabundle:/tmp/pki
    environment:
      FORCE_TRUST_ANCHORS_UPDATE: 1
      TRUST_ANCHORS_TARGET: /tmp/certificates
      CA_BUNDLE_TARGET: /tmp/pki

  db:
    image: mysql:5
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"

  voms:
    image: italiangrid/voms:centos7-stable
    container_name: voms
    hostname: voms
    entrypoint: sleep infinity
    links:
      - db
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./assets/vomses:/etc/vomses
      - ./assets/vomsdir:/etc/grid-security/vomsdir
      - ./assets/scripts:/scripts
      - ./assets/certs:/etc/grid-security/certs

volumes:
  trustanchors:
  cabundle:
  db_data: