# SPDX-FileCopyrightText: 2024 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: EUPL-1.2

[ test6 ]

pkeyopt                = ec_paramgen_curve:secp224r1
default_keyfile        = ${ENV::CA_NAME}/certs/test6.key.pem
distinguished_name     = test6_dn
prompt                 = no
output_password        = pass
default_md             = sha512
x509_extensions        = test6_extensions

[ test6_dn ]

C                      = IT
O                      = IGI
CN                     = Test6

[ test6_extensions ]

basicConstraints       = critical,CA:FALSE
subjectKeyIdentifier   = hash
keyUsage               = critical, nonRepudiation, digitalSignature, keyEncipherment
authorityKeyIdentifier = keyid, issuer
subjectAltName         = email:test6@cnaf.infn.it