# SPDX-FileCopyrightText: 2024 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: EUPL-1.2

[ test8 ]

pkeyopt                = ec_paramgen_curve:prime256v1
default_keyfile        = ${ENV::CA_NAME}/certs/test8.key.pem
distinguished_name     = test8_dn
prompt                 = no
output_password        = pass
default_md             = sha512
x509_extensions        = test8_extensions

[ test8_dn ]

C                      = IT
O                      = IGI
CN                     = Test8

[ test8_extensions ]

basicConstraints       = critical,CA:FALSE
subjectKeyIdentifier   = hash
keyUsage               = critical, nonRepudiation, digitalSignature, keyEncipherment
authorityKeyIdentifier = keyid, issuer
subjectAltName         = email:test8@cnaf.infn.it