# SPDX-FileCopyrightText: 2024 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: EUPL-1.2

[ voms_test_example_ec ]

pkeyopt                = ec_paramgen_curve:prime256v1
default_keyfile        = ${ENV::CA_NAME}/certs/voms_test_example_ec.key.pem
distinguished_name     = voms_test_example_dn
prompt                 = no
encrypt_key            = no
default_md             = sha512
x509_extensions        = voms_test_example_extensions

# reuse dn and extensions from voms_test_example
